sudo: required

env:
  - VERSION=5

services:
  - docker

before_install:
  - docker build -t nanobox/elasticsearch:$VERSION ./$VERSION

script: sudo test/run_all.sh $VERSION

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - "echo \"Branch: '$BRANCH'; Version: '$VERSION'\";"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/elasticsearch ./${VERSION};
  # `$VERSION-beta` tag is always pushed (master or any dev branch)
  - docker tag ${NAMESPACE}/elasticsearch ${NAMESPACE}/elasticsearch:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/elasticsearch:${VERSION}-beta;
  # `beta` tag is always pushed (master or any dev branch)
  - if [ "$VERSION" == "5" ]; then
    docker tag ${NAMESPACE}/elasticsearch ${NAMESPACE}/elasticsearch:beta;
    docker push ${REMOTE}${NAMESPACE}/elasticsearch:beta;
    fi
  # `latest` tag is only pushed on master && most recent version
  - if [ "$BRANCH" == "master" ] && [ "$VERSION" == "5" ]; then
    docker push ${REMOTE}${NAMESPACE}/elasticsearch;
    fi
  # `$VERSION` (latest/stable implied) tag is only pushed on master. tag branch for clarity otherwise (`$VERSION-$BRANCH`)
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/elasticsearch ${NAMESPACE}/elasticsearch:${VERSION};
    docker push ${REMOTE}${NAMESPACE}/elasticsearch:${VERSION};
    else
    docker tag ${NAMESPACE}/elasticsearch ${NAMESPACE}/elasticsearch:${VERSION}-${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/elasticsearch:${VERSION}-${BRANCH//\//_};
    fi
